# file: roles/oracle-jdk/meta/main.yml
---
galaxy_info:
  author: Maksud Sharif
  description: Deploy Oracle JDK
  company: Armedia

  license: GPLv2

  min_ansible_version: 2.0

  platforms:
  - name: EL
    versions:
    - 6
    - 7

  galaxy_tags:
  - Java
  - JDK
  - Oracle
  - EL

dependencies: []
version: 0.0.1