# Run Post installation tasks
---
- name: Run post-installation tasks
  block:
    - name: Start {{ solr_service_name }}
      shell: "service {{ solr_service_name }} start"
      become: yes
      become_user: root
      
    - name: Check Solr {{ solr_version }} PID
      shell: "cat {{ solr_home }}/bin/solr-{{ solr_port }}.pid | awk '{if(NR<2)print}'"
      register: solr_pid
      become: yes
      become_user: root
    
    - name: Check Solr Process {{ solr_pid.stdout }} is running on Port {{ solr_port }}
      shell: "lsof -i :{{ solr_port }} | sed -n '1!p' | awk '{print $2}'"
      register: pid_on_port
      become: yes
      become_user: root
    
    - fail:
        msg: "Solr not running on port {{ solr_port }}"
      when: solr_pid.stdout != pid_on_port.stdout
  when: solr_should_start == true